import { doc, setDoc } from "firebase/firestore";
import React, { useEffect, useMemo, useState } from "react";
import { db } from "../../../firebase/config";
import { useTheme } from "../../../firebase/hooks";
import type { ThemeSettings } from "../../../types";
import { FONTS, PRESETS } from "../../ThemeControl";

const COLORS: { key: keyof Pick<ThemeSettings, "primaryColor" | "secondaryColor" | "accentColor" | "backgroundColor" | "navbarColor" | "footerColor">; label: string }[] = [
  { key: "primaryColor", label: "Primary" }, { key: "secondaryColor", label: "Secondary" }, { key: "accentColor", label: "Accent" }, { key: "backgroundColor", label: "Page" }, { key: "navbarColor", label: "Navigation" }, { key: "footerColor", label: "Footer" },
];

const CompactThemeControl: React.FC = () => {
  const stored = useTheme();
  const [draft, setDraft] = useState<ThemeSettings>(stored);
  const [query, setQuery] = useState("");
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  useEffect(() => setDraft(stored), [stored]);
  const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(stored), [draft, stored]);
  const presets = useMemo(() => PRESETS.filter((preset) => preset.name.toLowerCase().includes(query.trim().toLowerCase())), [query]);
  const save = async () => { setSaving(true); setNotice(""); try { await setDoc(doc(db, "theme", "settings"), { ...draft, updatedAt: new Date().toISOString() }, { merge: true }); setNotice("Theme applied successfully."); } catch (error) { setNotice(`Error: ${String((error as Error).message || error)}`); } finally { setSaving(false); } };
  return <div className="space-y-5 pb-20">
    <header className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-600">Appearance studio</p><h2 className="mt-1 text-2xl font-black text-slate-900">Theme Control</h2><p className="mt-1 text-sm text-slate-500">Set the global palette and typography from one compact workspace.</p></div><div className="flex gap-2"><button disabled={!changed || saving} onClick={() => setDraft(stored)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-black text-slate-600 disabled:opacity-40">Reset</button><button disabled={!changed || saving} onClick={() => void save()} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-black text-white shadow-lg shadow-indigo-100 disabled:opacity-40">{saving ? "Applying…" : changed ? "Apply changes" : "Theme saved"}</button></div></div>{notice && <p className={`mt-4 rounded-xl px-3 py-2 text-xs font-bold ${notice.startsWith("Error:") ? "bg-rose-50 text-rose-700" : "bg-emerald-50 text-emerald-700"}`}>{notice}</p>}</header>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-black text-slate-900">Palette</h3><p className="text-xs text-slate-400">Click a swatch to change its color.</p></div><div className="flex overflow-hidden rounded-lg border border-slate-200">{COLORS.map(({ key }) => <span key={key} className="h-7 w-7" style={{ background: draft[key] }} />)}</div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{COLORS.map(({ key, label }) => <label key={key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-indigo-300"><span className="relative h-9 w-9 overflow-hidden rounded-lg border border-black/10" style={{ background: draft[key] }}><input type="color" value={draft[key]} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))} className="absolute inset-0 h-full w-full cursor-pointer opacity-0" /></span><span><span className="block text-xs font-black text-slate-700">{label}</span><span className="font-mono text-[10px] uppercase text-slate-400">{draft[key]}</span></span></label>)}</div><div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2">{(["fontFamily", "headingFont"] as const).map((key) => <label key={key} className="text-xs font-black text-slate-500">{key === "fontFamily" ? "Body font" : "Heading font"}<select value={draft[key]} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-semibold text-slate-700" style={{ fontFamily: draft[key] }}>{FONTS.map((font) => <option key={font} value={font}>{font.replaceAll("'", "").split(",")[0]}</option>)}</select></label>)}</div></section>

      <aside className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="px-5 py-4" style={{ background: draft.navbarColor }}><div className="flex items-center justify-between text-white"><strong style={{ fontFamily: draft.headingFont }}><span style={{ color: draft.accentColor }}>Syed's</span> Lab</strong><span className="text-[10px] text-white/60">Preview</span></div></div><div className="p-5" style={{ background: draft.backgroundColor }}><p className="text-[10px] font-black uppercase tracking-widest" style={{ color: draft.secondaryColor }}>Research laboratory</p><h3 className="mt-2 text-xl font-black" style={{ color: draft.primaryColor, fontFamily: draft.headingFont }}>Ideas into meaningful research.</h3><p className="mt-2 text-xs leading-5 text-slate-500" style={{ fontFamily: draft.fontFamily }}>A compact preview of headings, body copy, buttons and surface colors.</p><button className="mt-4 rounded-lg px-3 py-2 text-xs font-black text-white" style={{ background: draft.secondaryColor }}>Explore research</button></div><div className="h-8" style={{ background: draft.footerColor }} /></aside>
    </div>

    <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black text-slate-900">Theme presets</h3><p className="text-xs text-slate-400">Choose a preset, then apply it from the top bar.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search presets…" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm sm:w-64" /></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{presets.map((preset) => <button key={preset.name} onClick={() => setDraft(preset.settings)} className="rounded-xl border border-slate-200 p-3 text-left transition hover:border-indigo-300 hover:bg-indigo-50/40"><div className="flex h-8 overflow-hidden rounded-lg">{[preset.settings.primaryColor, preset.settings.secondaryColor, preset.settings.accentColor, preset.settings.backgroundColor].map((color, index) => <span key={index} className="flex-1" style={{ background: color }} />)}</div><p className="mt-2 truncate text-xs font-black text-slate-700">{preset.name}</p><p className="mt-0.5 truncate text-[10px] text-slate-400">{preset.settings.headingFont.replaceAll("'", "").split(",")[0]}</p></button>)}</div></section>
  </div>;
};
export default CompactThemeControl;
