import React, { useEffect, useState } from "react";
import type { ResearchIdea } from "../../../types";
import AdminModal from "../../components/AdminModal";
import { type ResearchIdeaDraft, updateResearchIdea } from "./researchIdeaService";

const toDraft = (idea: ResearchIdea): ResearchIdeaDraft => ({ title: idea.title || "", shortDescription: idea.shortDescription || "", fullDescription: idea.fullDescription || "", tags: idea.tags || [], isPublished: idea.isPublished !== false, isHidden: idea.isHidden === true, isFlagged: idea.isFlagged === true, isPinned: idea.isPinned === true });
const ResearchIdeaEditor: React.FC<{ idea: ResearchIdea | null; onClose: () => void; onSaved?: () => void }> = ({ idea, onClose, onSaved }) => {
  const [draft, setDraft] = useState<ResearchIdeaDraft | null>(idea ? toDraft(idea) : null);
  const [tags, setTags] = useState(idea?.tags?.join(", ") || "");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { setDraft(idea ? toDraft(idea) : null); setTags(idea?.tags?.join(", ") || ""); setError(""); }, [idea]);
  if (!idea || !draft) return null;
  const set = <K extends keyof ResearchIdeaDraft>(key: K, value: ResearchIdeaDraft[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const save = async () => { if (!draft.title.trim() || !draft.shortDescription.trim() || !draft.fullDescription.trim()) { setError("Title, summary, and full description are required."); return; } setSaving(true); setError(""); try { await updateResearchIdea(idea.id, { ...draft, title: draft.title.trim(), shortDescription: draft.shortDescription.trim(), fullDescription: draft.fullDescription.trim(), tags: tags.split(",").map((item) => item.trim()).filter(Boolean) }); onSaved?.(); onClose(); } catch (failure) { setError(String((failure as Error).message || failure)); } finally { setSaving(false); } };
  const field = "w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-800 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100";
  return <AdminModal open title="Edit research idea" description={`Update ${idea.authorName}'s submitted idea.`} onClose={() => !saving && onClose()} width="820px" footer={<div className="flex justify-end gap-3"><button onClick={onClose} disabled={saving} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Cancel</button><button onClick={() => void save()} disabled={saving} className="rounded-xl bg-indigo-600 px-6 py-2.5 text-sm font-black text-white disabled:opacity-50">{saving ? "Saving…" : "Save changes"}</button></div>}><div className="grid gap-5"><label className="grid gap-2 text-xs font-black uppercase tracking-wider text-slate-500">Title<input className={field} value={draft.title} onChange={(event) => set("title", event.target.value)} /></label><label className="grid gap-2 text-xs font-black uppercase tracking-wider text-slate-500">Summary<textarea className={field} rows={3} value={draft.shortDescription} onChange={(event) => set("shortDescription", event.target.value)} /></label><label className="grid gap-2 text-xs font-black uppercase tracking-wider text-slate-500">Full description<textarea className={field} rows={8} value={draft.fullDescription} onChange={(event) => set("fullDescription", event.target.value)} /></label><label className="grid gap-2 text-xs font-black uppercase tracking-wider text-slate-500">Tags<input className={field} value={tags} onChange={(event) => setTags(event.target.value)} placeholder="AI, robotics, sustainability" /></label><div className="grid gap-3 sm:grid-cols-2">{([['isPublished','Published'],['isPinned','Pinned'],['isHidden','Hidden'],['isFlagged','Flagged']] as const).map(([key,label]) => <label key={key} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700"><span>{label}</span><input type="checkbox" checked={Boolean(draft[key])} onChange={(event) => set(key, event.target.checked)} /></label>)}</div>{error && <p className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</p>}</div></AdminModal>;
};
export default ResearchIdeaEditor;
