import React, { useMemo, useState } from "react";
import AppIcon from "../../../components/AppIcon";
import type { Comment, ResearchIdea } from "../../../types";
import AdminModal from "../../components/AdminModal";
import AdminPage from "../../components/AdminPage";
import ConfirmDialog from "../../components/ConfirmDialog";
import ResearchIdeaEditor from "./ResearchIdeaEditor";
import { patchResearchIdea, removeResearchComment, removeResearchIdea } from "./researchIdeaService";
import { useIdeaComments, useResearchIdeaAdmin } from "./useResearchIdeaAdmin";

type Filter = "all" | "published" | "hidden" | "flagged" | "pinned";
type PendingDelete = { type: "idea"; item: ResearchIdea } | { type: "comment"; item: Comment } | null;

const ResearchIdeasPage: React.FC = () => {
  const { ideas, loading, error } = useResearchIdeaAdmin();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [sort, setSort] = useState("newest");
  const [editing, setEditing] = useState<ResearchIdea | null>(null);
  const [details, setDetails] = useState<ResearchIdea | null>(null);
  const [pendingDelete, setPendingDelete] = useState<PendingDelete>(null);
  const [busyId, setBusyId] = useState("");
  const [notice, setNotice] = useState("");
  const { comments, loading: commentsLoading } = useIdeaComments(details?.id);

  const stats = useMemo(() => ({ total: ideas.length, published: ideas.filter((item) => item.isPublished).length, hidden: ideas.filter((item) => item.isHidden).length, flagged: ideas.filter((item) => item.isFlagged).length, pinned: ideas.filter((item) => item.isPinned).length }), [ideas]);
  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase();
    const result = ideas.filter((idea) => (filter === "all" || (filter === "published" && idea.isPublished) || (filter === "hidden" && idea.isHidden) || (filter === "flagged" && idea.isFlagged) || (filter === "pinned" && idea.isPinned)) && (!term || `${idea.title} ${idea.authorName} ${idea.tags?.join(" ")}`.toLowerCase().includes(term)));
    return [...result].sort((a, b) => sort === "oldest" ? a.createdAt.localeCompare(b.createdAt) : sort === "comments" ? (b.commentCount || 0) - (a.commentCount || 0) : sort === "activity" ? (b.updatedAt || b.createdAt).localeCompare(a.updatedAt || a.createdAt) : b.createdAt.localeCompare(a.createdAt));
  }, [filter, ideas, search, sort]);

  const patch = async (idea: ResearchIdea, values: Partial<ResearchIdea>, success = "Research idea updated.") => { setBusyId(idea.id); setNotice(""); try { await patchResearchIdea(idea.id, values); setNotice(success); } catch (failure) { setNotice(`Error: ${String((failure as Error).message || failure)}`); } finally { setBusyId(""); } };
  const confirmDelete = async () => { if (!pendingDelete) return; setBusyId(pendingDelete.item.id); setNotice(""); try { if (pendingDelete.type === "idea") { await removeResearchIdea(pendingDelete.item.id); if (details?.id === pendingDelete.item.id) setDetails(null); setNotice("Research idea and its discussion were deleted."); } else { await removeResearchComment(pendingDelete.item.id); if (details) await patchResearchIdea(details.id, { commentCount: Math.max(0, (details.commentCount || 1) - 1) }); setNotice("Comment deleted."); } setPendingDelete(null); } catch (failure) { setNotice(`Error: ${String((failure as Error).message || failure)}. Deploy the included Firestore rules and retry.`); } finally { setBusyId(""); } };
  const filters: Filter[] = ["all", "published", "hidden", "flagged", "pinned"];

  return <AdminPage eyebrow="Research operations" title="Research Ideas" description="Review submissions, edit content, moderate visibility, and manage discussions from one consistent workspace." toolbar={<div className="grid gap-3 lg:grid-cols-[1fr_auto]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, author or tag…" className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-500" /><select value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="comments">Most comments</option><option value="activity">Recent activity</option></select></div>}>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{Object.entries(stats).map(([label, value]) => <button key={label} onClick={() => setFilter(label === "total" ? "all" : label as Filter)} className={`rounded-2xl border p-4 text-left shadow-sm transition ${filter === (label === "total" ? "all" : label) ? "border-indigo-300 bg-indigo-50" : "border-slate-200 bg-white"}`}><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p></button>)}</div>
    <div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-xs font-black capitalize ${filter === item ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{item}</button>)}<span className="ml-auto self-center text-xs font-bold text-slate-400">{filtered.length} results</span></div>
    {notice && <div role="status" className={`rounded-2xl border px-4 py-3 text-sm font-bold ${notice.startsWith("Error:") ? "border-rose-200 bg-rose-50 text-rose-700" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{notice}</div>}
    {error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700">{error}</div>}
    {loading ? <div className="rounded-3xl border border-slate-200 bg-white py-20 text-center text-sm font-bold text-slate-400">Loading research ideas…</div> : filtered.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-300 bg-white py-20 text-center"><div className="mx-auto w-fit text-slate-300"><AppIcon name="ideas" size={42} /></div><p className="mt-3 font-bold text-slate-500">No ideas match these filters.</p></div> : <div className="grid gap-4">{filtered.map((idea) => <article key={idea.id} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex flex-col gap-4 xl:flex-row xl:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{idea.isPinned && <Badge text="Pinned" tone="amber" />}{idea.isFlagged && <Badge text="Flagged" tone="rose" />}{idea.isHidden && <Badge text="Hidden" tone="slate" />}{idea.isPublished && <Badge text="Published" tone="emerald" />}</div><h3 className="mt-3 text-lg font-black leading-6 text-slate-900">{idea.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{idea.shortDescription || idea.fullDescription}</p><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs font-semibold text-slate-400"><span>{idea.authorName}</span><span>{new Date(idea.createdAt).toLocaleDateString()}</span><span>{idea.commentCount || 0} comments</span></div>{idea.tags?.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{idea.tags.map((tag) => <span key={tag} className="rounded-full bg-sky-50 px-2.5 py-1 text-[10px] font-bold text-sky-700">{tag}</span>)}</div>}</div><div className="grid shrink-0 grid-cols-2 gap-2 sm:flex sm:flex-wrap xl:max-w-[390px] xl:justify-end"><Action label="View" onClick={() => setDetails(idea)} /><Action label="Edit" onClick={() => setEditing(idea)} primary /><Action label={idea.isPublished ? "Unpublish" : "Publish"} disabled={busyId === idea.id} onClick={() => void patch(idea, { isPublished: !idea.isPublished })} /><Action label={idea.isHidden ? "Show" : "Hide"} disabled={busyId === idea.id} onClick={() => void patch(idea, { isHidden: !idea.isHidden })} /><Action label={idea.isPinned ? "Unpin" : "Pin"} disabled={busyId === idea.id} onClick={() => void patch(idea, { isPinned: !idea.isPinned })} /><Action label={idea.isFlagged ? "Clear flag" : "Flag"} disabled={busyId === idea.id} onClick={() => void patch(idea, { isFlagged: !idea.isFlagged })} /><Action label="Delete" danger onClick={() => setPendingDelete({ type: "idea", item: idea })} /></div></div></article>)}</div>}
    <ResearchIdeaEditor idea={editing} onClose={() => setEditing(null)} />
    <AdminModal open={Boolean(details)} title="Research idea details" description={details ? `Submitted by ${details.authorName}` : ""} onClose={() => setDetails(null)} width="860px" footer={details && <div className="flex justify-between"><button onClick={() => setPendingDelete({ type: "idea", item: details })} className="rounded-xl bg-rose-50 px-4 py-2.5 text-sm font-black text-rose-700">Delete idea</button><button onClick={() => { setEditing(details); setDetails(null); }} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-black text-white">Edit idea</button></div>}><IdeaDetails idea={details} comments={comments} commentsLoading={commentsLoading} onDeleteComment={(comment) => setPendingDelete({ type: "comment", item: comment })} /></AdminModal>
    <ConfirmDialog open={Boolean(pendingDelete)} title={pendingDelete?.type === "idea" ? "Delete research idea?" : "Delete comment?"} message={pendingDelete?.type === "idea" ? `“${pendingDelete.item.title}” will be permanently removed.` : "This comment will be permanently removed."} danger confirmLabel="Delete permanently" busy={Boolean(busyId)} onCancel={() => !busyId && setPendingDelete(null)} onConfirm={() => void confirmDelete()} />
  </AdminPage>;
};

const Badge: React.FC<{ text: string; tone: "amber" | "rose" | "slate" | "emerald" }> = ({ text, tone }) => <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${tone === "amber" ? "bg-amber-100 text-amber-800" : tone === "rose" ? "bg-rose-100 text-rose-700" : tone === "emerald" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{text}</span>;
const Action: React.FC<{ label: string; onClick: () => void; primary?: boolean; danger?: boolean; disabled?: boolean }> = ({ label, onClick, primary, danger, disabled }) => <button type="button" disabled={disabled} onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-black transition disabled:opacity-40 ${danger ? "bg-rose-50 text-rose-700" : primary ? "bg-indigo-600 text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-slate-400"}`}>{label}</button>;
const IdeaDetails: React.FC<{ idea: ResearchIdea | null; comments: Comment[]; commentsLoading: boolean; onDeleteComment: (comment: Comment) => void }> = ({ idea, comments, commentsLoading, onDeleteComment }) => idea ? <div className="space-y-6"><div><div className="flex flex-wrap gap-2">{idea.tags?.map((tag) => <span key={tag} className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">{tag}</span>)}</div><h3 className="mt-4 text-2xl font-black text-slate-900">{idea.title}</h3><p className="mt-3 text-sm font-semibold leading-6 text-slate-600">{idea.shortDescription}</p><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-700">{idea.fullDescription}</p></div><section className="border-t border-slate-100 pt-5"><h4 className="font-black text-slate-900">Comments ({comments.length})</h4>{commentsLoading ? <p className="mt-4 text-sm text-slate-400">Loading comments…</p> : comments.length === 0 ? <p className="mt-4 text-sm text-slate-400">No comments yet.</p> : <div className="mt-4 grid gap-3">{comments.map((comment) => <div key={comment.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-slate-800">{comment.authorName}</p><p className="text-[11px] text-slate-400">{new Date(comment.createdAt).toLocaleString()}</p></div><button onClick={() => onDeleteComment(comment)} className="text-xs font-black text-rose-600">Delete</button></div><p className="mt-3 text-sm leading-6 text-slate-600">{comment.content}</p></div>)}</div>}</section></div> : null;
export default ResearchIdeasPage;
